print("\n")
print(".d8888. db   db  .d8b.  d8888b. d8888b.")
print("88'  YP 88   88 d8' `8b 88  `8D 88  `8D") 
print("`8bo.   88ooo88 88ooo88 88oobY' 88   88") 
print("  `Y8b. 88~~~88 88~~~88 88`8b   88   88") 
print("db   8D 88   88 88   88 88 `88. 88  .8D") 
print("`8888Y' YP   YP YP   YP 88   YD Y8888D'") 
print("=======================================")
print("|            ::CREDITS::              |")
print("=======================================")
print("|NotHawthorne...........Lead Developer|")
print("|Laduguer................World Builder|")
print("|Kaev...................LUA Programmer|")
print("|Rochet2..........Lead Eluna Developer|")
print("|Tony.......................Ideaguy #1|")
print("|/wpsg/...............First Players <3|")
print("|EmuDevs.........Support and Community|")
print("=======================================")
print("|          ::CONTACT INFO::           |")
print("=======================================")
print("|Website: http://shard.ddns.net/      |")
print("|E-Mail: nothawthorne@cock.li         |")
print("|Skype: vulcan445                     |")
print("=======================================")
print("\n")